language: csharp
solution: FileSplitter.sln
mono:
 - latest
before_deploy:
 - cd /home/travis/build/dubasdey/File-Splitter/FileSplitter/bin/Release/
 - zip FileSplitter.zip fSplit.exe fSplit.exe.config ../../changelog.txt ../../LICENSE ../../README.md
deploy:
  provider: releases
  api_key: $GITAPI
  file: "/home/travis/build/dubasdey/File-Splitter/FileSplitter/bin/Release/FileSplitter.zip"
  skip_cleanup: true
  on:
    tags: true
