language: csharp
solution: FileSplitter.sln
mono:
 - latest
before_deploy:
 - cd bin/Release/
 - zip FileSplitter.zip fSplit.exe fSplit.exe.config ../../changelog.txt ../../LICENSE ../../README.md
 - cp FileSplitter.zip ../../FileSplitter.zip
deploy:
  provider: releases
  api_key: $GITAPI
  file: "FileSplitter.zip"
  skip_cleanup: true
  on:
    tags: true
